class_name BackNavigation
extends RefCounted

# 현재 보이는 UI 상태에서 시스템 뒤로가기가 수행할 한 가지 작업을 고른다.
# 실제 화면 변경은 MainApp이 action에 연결한 callback이 수행한다.

enum Action {
	CANCEL_RESTORE,
	CANCEL_CARD_DELETE,
	CANCEL_DISCARD_CHANGES,
	CANCEL_CREATE_DECK,
	CANCEL_RENAME_DECK,
	CANCEL_DELETE_DECK,
	DISMISS_ADD_DECK_MENU,
	DISMISS_LIBRARY_MENU,
	DISMISS_CARD_MENU,
	DISMISS_DECK_MENU,
	CANCEL_EXIT,
	RETURN_LIBRARY_FROM_SETTINGS,
	SHOW_EXIT_CONFIRMATION,
	CLOSE_CARD_EDITOR,
	CLOSE_CARD_DETAIL,
	CLOSE_CARD_LIST,
	CANCEL_STUDY_SETUP,
	RETURN_LIBRARY_FROM_READY,
	RETURN_TO_STUDY_READY,
}

const PRIORITY := [
	Action.CANCEL_RESTORE,
	Action.CANCEL_CARD_DELETE,
	Action.CANCEL_DISCARD_CHANGES,
	Action.CANCEL_CREATE_DECK,
	Action.CANCEL_RENAME_DECK,
	Action.CANCEL_DELETE_DECK,
	Action.DISMISS_ADD_DECK_MENU,
	Action.DISMISS_LIBRARY_MENU,
	Action.DISMISS_CARD_MENU,
	Action.DISMISS_DECK_MENU,
	Action.CANCEL_EXIT,
	Action.RETURN_LIBRARY_FROM_SETTINGS,
	Action.SHOW_EXIT_CONFIRMATION,
	Action.CLOSE_CARD_EDITOR,
	Action.CLOSE_CARD_DETAIL,
	Action.CLOSE_CARD_LIST,
	Action.CANCEL_STUDY_SETUP,
	Action.RETURN_LIBRARY_FROM_READY,
]


static func resolve(active_actions: Dictionary) -> Action:
	for action: Action in PRIORITY:
		if active_actions.get(action, false):
			return action
	return Action.RETURN_TO_STUDY_READY
